### ISSUE TITLE
Install-Package Westwind.Scripting -IncludePreRelease; Error; Install-Package : Project 'Default' is not found.

### ISSUE THREAD

**Issue by JohnRanger** [RickStrahl/Westwind.Scripting#1]
Hi Rick,

when I try to install your NuGet package into one of my projects, I get the following error:

```
Install-Package : Project 'Default' is not found.
At line:1 char:1
+ Install-Package Westwind.Scripting  -IncludePreRelease
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Default:String) [Install-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
```

And yes - my project is not called 'default'. So the error message makes sense - but should your nuget package not install into any existing project?

With kind regards,

John

**Comment by RickStrahl** [comment]
Not sure. What type of project and what framework is targeted? Note it only works with Full .NET Framework not with .NET Core.

It just looks like an invalid package name, meaning you're probably trying to install this into a framework that isn't supported.
