### ISSUE TITLE
Conflict with Microsoft.VisualStudio.Web.CodeGeneration and Westwind.Scripting 1.2.1

### ISSUE THREAD

**Issue by xantari** [RickStrahl/Westwind.Scripting#18]
When you install Westwind.Scripting 1.2.1 on an existing .NET Core 6.0 MVC project that has never used the code analysis features that are required to scaffold new views using (Microsoft.VisualStudio.Web.CodeGeneration) you are unable to properly get scaffolding to work afterwards.

Steps to Recreate:

1. Create a new .NET Core 6.0 MVC Project
2. Install Westwind.Script 1.2.1
3. Right click the Views folder, and click "Add", then click "View", then pick Razor View.

Pick any view with a model class, here is an example:
![image](https://user-images.githubusercontent.com/6610039/235371392-87db46dc-99cb-45fe-833e-4ea806984577.png)

Click Add

![image](https://user-images.githubusercontent.com/6610039/235371402-4097f33d-de98-47a8-acab-689566d4cc00.png)

You get the above error message.

In further analysis it looks like this is erroring behind the scenes (very hard to see why). But I think I know reason.

Your nuget using packages that cause conflict with adding Microsoft.VisualStudio.Web.CodeGeneration to project that is required to support visual studio scaffolding. Here is the nuget restore chain if you try to do what visual studio does behind the scenes:

![image](https://user-images.githubusercontent.com/6610039/235371478-653bb939-edc7-4c94-b9ab-000e8215dd1d.png)

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1107	Version conflict detected for Microsoft.CodeAnalysis.Common. Install/reference Microsoft.CodeAnalysis.Common 4.4.0 directly to project WebApplication2 to resolve this issue. 
 WebApplication2 -> Westwind.Scripting 1.2.1 -> Microsoft.CodeAnalysis.Scripting.Common 4.4.0 -> Microsoft.CodeAnalysis.Common (= 4.4.0) 
 WebApplication2 -> Microsoft.VisualStudio.Web.CodeGeneration 6.0.13 -> Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore 6.0.13 -> Microsoft.DotNet.Scaffolding.Shared 6.0.13 -> Microsoft.CodeAnalysis.CSharp.Features 4.0.0 -> Microsoft.CodeAnalysis.Common (= 4.0.0).	WebApplication2	C:\TFS\WebApplication2\WebApplication2\WebApplication2.csproj	1

**Comment by RickStrahl** [comment]
Took a look at this but can't duplicate what you see. 

* Created a new MVC project (.NET 6.0)
* Added a new view in the Home folder

No error - code compiles and runs and I can also call the scripting library from the controller to execute code.

```cs
public class HomeController : Controller
{
    public IActionResult Index()
    {

        var model = new IndexModel();

        var script = new CSharpScriptExecution() { SaveGeneratedCode = true };
        script.AddDefaultReferencesAndNamespaces();

        var code = $@"
// pick up and cast parameters
int num1 = (int) @0;   // same as parameters[0];
int num2 = (int) @1;   // same as parameters[1];

var result = $""{{num1}} + {{num2}} = {{(num1 + num2)}}"";

Console.WriteLine(result);  // just for kicks in a test

return result;
";

        // should return a string: (`"10 + 20 = 30"`)
        model.Result = script.ExecuteCode<string>(code, 10, 20);

        if (script.Error)
        {
            model.Error = $"Error: {script.ErrorMessage}\n" +
                          script.GeneratedClassCodeWithLineNumbers;
        }


        return Json(model);
    }

    public class IndexModel
    {
        public string Result { get; set; }
        public string Error { get; set;  }
    }

}
```


I can see like there might be an issue with version conflicts in CodeAnalyzers, but NuGet should be able to consolidate assuming the versions aren't vastly out of sync. But it clearly works with the current production defaults for .NET 6.0.

**Comment by xantari** [comment]
Attached is a sample project that it occurs in.

Here are the steps:

1. Load WebApplication2.sln
2. Right click Views folder and add new Item
3. Click Razor View:
![image](https://github.com/RickStrahl/Westwind.Scripting/assets/6610039/d8a2e610-60bc-47c3-8c1b-cb741e836750)

4. Pick all options as shown in this picture:
![image](https://github.com/RickStrahl/Westwind.Scripting/assets/6610039/fb1ade09-b123-40d0-b2b1-13f0d8861a79)

5. Hit Add

This is what I get. Let me know if you get same issue. I am using Visual Studio 2022 (17.5.2)

![image](https://github.com/RickStrahl/Westwind.Scripting/assets/6610039/0ea425d1-211e-47c6-a56d-388f665e8173)


[WebApplication2.zip](https://github.com/RickStrahl/Westwind.Scripting/files/11464794/WebApplication2.zip)

**Comment by RickStrahl** [comment]
Hmmm... yes I see it fail too for the scaffolding View addition. Works if you add an empty view.

Upgrading the project to .NET 7.0 and updating the libraries works.

I think the problem is that Visual Studio is using the latest libraries and they are incompatible with the older versions that you are still using. Problem is that the newer package doesn't work with .NET 6.0 - it requires 7.0.

So that puts us in a shitty spot:

* Keep the older version references: Incompatible with Visual Studio
* Use the newer versions: incompatible with .NET 6.0

Not sure what the solution is here. Not sure if there's a base line that would work in both scenarios. @richlander

**Comment by RickStrahl** [comment]
Closing as there's nothing that I know of we can do about this.
