### ISSUE TITLE
Support for .netcore31

### ISSUE THREAD

**Issue by AleRoe** [RickStrahl/Westwind.Scripting#2]
Hi Rick,

any plans for making this library available for netcore31?

Thanks
Alexander

**Comment by RickStrahl** [comment]
I'd like to but at the time this was not possible because .NET Core doesn't have an easy way to ship the compiler runtimes at the moment (or last I looked which was some time ago). This may change in the future but for now I don't think there's an easy way to get at the compiler.

**Comment by RickStrahl** [comment]
v1.0+ adds support for .NET Core.

New targets are:

* net462
* net60
* netstandard20


New version also adds async support, strongly typed overloads via generics, and a simple C# based Template engine.
