### ISSUE TITLE
Sandboxing code

### ISSUE THREAD

**Issue by zraffaele** [RickStrahl/Westwind.Scripting#20]
Hi,
as you know in .net core Microsoft has deprecated the CAS.
Have you think to an alternative to execute the code compiled at runtime in a security context?
For example the code that run do not save files on disk o do not naivgate on the internet
Thanks

**Comment by RickStrahl** [comment]
I don't think this is possible in .NET Core AFAI. 

Best thing you can do is have your host application run in a security environment that prevents issues.
