### ISSUE TITLE
Wrong code gets executed on second invoke of ExecuteCode

### ISSUE THREAD

**Issue by thedruggist** [RickStrahl/Westwind.Scripting#25]
When invoking the method ExecuteCode for a second time on the same instance of CSharpScriptExecution the code parameter is not used. The code from the first invoke is used. In my opinion this happens because after compiling the new assembly in ExecuteMethod the method CreateInstance should be invoked with parameter force = true

**Comment by RickStrahl** [comment]
Handled in #30.
